# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: -main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/checkout@v3
        with:
          node-version: "v21.2.0"

      - name: Install dependencies
        run: npm install

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start

      - name: Check PostgreSQL status
        run: |
          sudo service postgresql status

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-client

      # - name: Create PostgreSQL Database
      #   env:
      #     HOST: ${{ secrets.HOST }}
      #     DATABASE: ${{ secrets.DATABASE }}
      #     DB_Name: ${{ secrets.DB_NAME }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      #   run: |
      #     psql -h${{ secrets.HOST }}-U${{ secrets.DB_NAME }} -d${{ secrets.DATABASE }}-c "CREATE DATABASE ${{ secrets.DATABASE }};"

      - name: Update postgres user password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"

      - name: Create Users table
        env:
          HOST: ${{ secrets.HOST }}
          DB_Name: ${{ secrets.DB_NAME }}
          DATABASE: ${{ secrets.DATABASE }}
        run: |
          psql -h $HOST -U $DB_Name -d $DATABASE -c "CREATE TABLE Users (
            id UNIQUE NOT NULL,
            email VARCHAR(255) PRIMARY KEY,
            password VARCHAR(255) NOT NULL,
            firstName VARCHAR(255) NOT NULL,
            lastName VARCHAR(255) NOT NULL,
            account_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            account_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
          );"

      - name: Run tests
        env:
          HOST: ${{ secrets.HOST }}
          DATABASE: ${{ secrets.DATABASE }}
          DB_Name: ${{ secrets.DB_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm test

      - name: Execute exit 1 for failure testing
        if: failure()
        run: exit 1

      - name: Print on Success
        if: ${{ success() }}
        run: echo "The workflow run was successfull."
