name: build.js

on:
  push:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Web App
        run: zip -r webapp.zip ../webapp

      - name: Set up Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip
          unzip packer_1.8.3_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
        shell: bash

      - name: Set up Cloud SDK for the instance
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Verify gcloud CLI installation
        run: gcloud --version

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          chmod +x packer
          mv packer /usr/local/bin
        shell: bash

      - name: Run packer init
        run: packer init packer-GCP.pkr.hcl

      - name: Run `packer Build`
        id: packer_build
        run: |
          echo "Running packer build"
          packer build packer-GCP.pkr.hcl

          done
