name: PackerBuild.js

on:
  pull_request:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Web App
        run: zip -r webapp.zip ../webapp

      - name: Set up Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip
          unzip packer_1.8.3_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
        shell: bash

      - name: Set up Cloud SDK for the instance
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: "${{ secrets.GCP_SA_KEY  }}"
          export_default_credentials: true

      - name: Verify gcloud CLI installation
        run: gcloud --version

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          chmod +x packer
          mv packer /usr/local/bin
        shell: bash

      - name: Run packer init
        run: packer init ./packer-GCP/packer-GCP.pkr.hcl

      - name: Run `packer Build`
        id: packer_build
        run: |
          echo "Running packer build"
          packer build ./packer-GCP/packer-GCP.pkr.hcl

      # - name: create New Instance Template
      #   id: instance-templates
      #   run: |
      #     gcloud compute instance-templates create ${{secrets.INSTANCE_TEMP_NAME}} --project=assignment-04-414723 --machine-type=n1-standard-1 --network-interface=subnet=webapp,no-address --metadata=startup-script=sudo\ bash\ -c\ \'cat\ \>\ /opt/csye6225/webapp/.env\ \<\<EOT$'\n'DB_USER=webapp$'\n'DB_DIALECT=mysql$'\n'DB_NAME=webapp$'\n'DB_PASSWORD=${{secrets.GCP_INST_DB_PASSWORD}}$'\n'DB_HOST=${{secrets.GCP_DB_HOST}}$'\n'PORT=3306$'\n'EOT\'$'\n' --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=webapp-service-account-id@assignment-04-414723.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/cloud-platform --region=${{secrets.GCP_REGION}} --tags=webapp,allow-health-check --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=projects/assignment-04-414723/global/images/my-custom-image,kms-key=projects/assignment-04-414723/locations/${{secrets.GCP_REGION}}/keyRings/${{secrets.KRING}}/cryptoKeys/vm-key,mode=rw,size=100,type=pd-standard --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

      # - name: create managed instance group
      #   id: instance-group-templates
      #   run: |
      #     gcloud compute instance-groups managed rolling-action start-update ${{secrets.INSTANCE_GROUP_NAME}} --version=template=${{secrets.INSTANCE_TEMP_NAME}} --region=${{secrets.GCP_REGION}} --max-surge=0 --replacement-method=recreate

      # - name: wait for managed instance group to refresh
      #   id: wait-for-managed-instance-group-to-refresh
      #   run: |
      #     gcloud compute instance-groups managed wait-until ${{secrets.INSTANCE_GROUP_NAME}} --version-target-reached --region=${{secrets.GCP_REGION}}
