name: build.js

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run packer init
        run: packer init packer-GCP/packer-GCP.pkr.hcl

      # - name: Check Packer fmt
      #   id: fmt
      #   run: |
      #     echo pwd
      #     echo ls -la
      #     exit 1
      #     packer fmt -check ./packer-GCP/packer-GCP.pkr.hcl

      - name: Check Packer validate
        id: validate
        run: packer validate packer-GCP/packer-GCP.pkr.hcl

      - name: Check for fmt changes
        run: |
          if [ "${{ steps.fmt.outcome }}" == "failure" ]; then
            echo "Packer fmt modified files. Please run 'packer fmt' and commit the changes."
            exit 1
          fi

      - name: Check validate result
        run: |
          if [ "${{ steps.validate.outcome }}" == "failure" ]; then
            echo "Packer validation failed. Please fix the errors."
            exit 1
          fi
