name: build.js

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Web App
        run: zip -r webapp.zip ../webapps

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run packer init
        run: packer init packer-GCP/packer-GCP.pkr.hcl

      - name: Check Packer format
        id: fmt
        run: packer fmt -check packer-GCP/packer-GCP.pkr.hcl

      - name: Check Packer validate
        id: validate
        run: packer validate packer-GCP/packer-GCP.pkr.hcl
